name: Publish release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'versions.yml'

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install conventional-changelog-conventionalcommits

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.17.0
        with:
          github-token: ${{ secrets.PRIVATE_TOKEN }}
          git-user-name: 'WynntilsBot'
          git-user-email: 'admin@wynntils.com'
          pre-commit: ./.github/.pre-commit.js
          config-file-path: ./.github/.config.js
          skip-version-file: true
          skip-git-pull: true

      - name: Upload version information
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: gradle.properties

  build:
    runs-on: ${{ matrix.os }}
    needs: [changelog] # Build needs the new version number
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3 # Download version information from changelog
        with:
          name: version

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 16
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run custom gradle package
        run: gradle packageForRelease

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: 'releases/*'

  publish-release:
    needs: [ build, changelog ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Move all release artifacts into one folder
        shell: bash
        run: |
          mkdir releases
          mv artifacts/build*/* releases

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*
          tag_name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.clean_changelog }}
          target_commitish: ${{ github.sha }}

